server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateaway:
      routes:
        - id: SQALE-SERVICE
          uri: lb://SQALE-SERVICE
          predicates:
            - Path=/sqales/**
          filters:
            - name: CircuitBreaker
              args:
                name: SQALE-SERVICE
                fallbackuri: forward:/sqaleServiceFallBack
        - id: MAINTAINABILITYINDEX-SERVICE
          uri: lb://MAINTAINABILITYINDEX-SERVICE
          predicates:
            - Path=/maintainabilityindexs/**
          filters:
            - name: CircuitBreaker
              args:
                name: MAINTAINABILITYINDEX-SERVICE
                fallbackuri: forward:/maintainabilityServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exsposure:
        include: hystrix.stream

